"""add_session_uuid_to_models

Revision ID: d39147e10f62
Revises: c8adc359670e
Create Date: 2026-02-23 17:54:47.078573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd39147e10f62'
down_revision: Union[str, Sequence[str], None] = 'c8adc359670e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('session_uuid', sa.String(255), nullable=False))
    op.create_unique_constraint(None, 'message', ['session_uuid'])
    op.add_column('session', sa.Column('session_uuid',sa.String(255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'session_uuid')
    op.drop_constraint(None, 'message', type_='unique')
    op.drop_column('message', 'session_uuid')
    # ### end Alembic commands ###
